config/routes.rb
Rails.application.routes.draw do
  resources :games
  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_one_attached :rules
    has_many_attached :images
    has_one_attached :box
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :rule, :rules, :box, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre_del_juego %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Reglas %>
    <%= form.text_area :rule %>
  </div>

  <div class="field">
    <%= form.label :Reglas_en_archivo_pdf %>
    <%= form.file_field :rules %>
  </div>

  <div class="field">
    <%= form.label :Caja_del_tablero %>
    <%= form.file_field :box %>
  </div>

  <div class="field">
    <%= form.label :Piezas_y_partes_del_tablero %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Juegos</h1>

<table class="table table-dark table-bordered ">
  <thead>
    <tr class="text-center bg-primary">
      <th>Nombre del juego</th>
      <th>Reglas</th>
      <th>Reglas en pdf</th>
      <th>Tablero</th>
      <th>Piezas</th>
      <th>Detalle</th>
      <th>Editar</th>
      <th>Eliminar</th>

    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <p>
        <td ><%= game.rule %></td>
        </p>
        <td ><% game.rules %>
          <a class="text-white" href="<%= rails_blob_path(game.rules, disposition: "attachment") %>" > <u> Descargar </u> </a>
        </td>

        <td ><% game.box%> 
          <div class="form-group">
            <% if game.box.attached? %>
              <%= image_tag game.box, style: "-webkit-filter: grayscale(100%) height:100px;width:100px"%>
            <% end %>
          </div>
        </td>

        <td ><% game.images%> 
          <div class="form-group">
          <% if game.images.attached? %>
          <% game.images.each do |image| %>
          <%= image_tag image, style: "-webkit-filter: grayscale(100%) height:100px;width:100px" %>
          <% end %>
          </p>
          <% end %>
            </div>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Juego nuevo', new_game_path %>

app/views/games/new.html.erb
<h1>Juego nuevo</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre del juego:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Reglas:</strong>
  <%= @game.rule %>
</p>

<p>
  <strong>Reglas en pdf:</strong>
  <% @game.rules %>
    <a href="<%= rails_blob_path(@game.rules, disposition: "attachment") %>"><u>Reglas</u></a>
</p>

<p>
  <strong>Tablero</strong>
  <div class="form-group">
      <% if @game.box.attached? %>
        <%= image_tag @game.box, style: "-webkit-filter: grayscale(100%) height:150px;width:150px" %>
      <% end %>
  </div>
</p>

<p>
  <strong>Piezas</strong>
    <div class="form-group">
      <% if @game.images.attached? %>
        <% @game.images.each do |image| %>
          <%= image_tag image, style: "-webkit-filter: grayscale(100%) height:150px;width:150px" %>
        <% end %>
      <% end %>
    </div>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>